/**
 * Do not edit directly, this file was auto-generated.
 */

export const primitivesPurple50 = "#FAF7FF"; // Purple Tint — lightest surface
export const primitivesPurple100 = "#F0E9FB"; // Purple Light — subtle bg
export const primitivesPurple600 = "#7C35EB"; // Hover / dark mode
export const primitivesPurple700 = "#6D28D9"; // Purple Heart — main brand
export const primitivesPurple800 = "#4E22B0";
export const primitivesPurple900 = "#3B1A8A"; // Purple darkest
export const primitivesNeutral0 = "#FFFFFF"; // Pure White
export const primitivesNeutral50 = "#FCFCFC"; // Alabaster
export const primitivesNeutral100 = "#F7F8FA"; // Shatlevka — page bg
export const primitivesNeutral200 = "#EBEBEB"; // Warm Gray — borders
export const primitivesNeutral400 = "#AEAEAE"; // Soft Gray — disabled
export const primitivesNeutral600 = "#717182"; // Storm Gray — secondary text
export const primitivesNeutral800 = "#1E1E1E"; // PopUp Gray
export const primitivesNeutral950 = "#0A0A0A"; // Cod Gray — primary text
export const primitivesGreen100 = "#DCFCE7"; // Persian Light — success bg
export const primitivesGreen700 = "#009689"; // Persian Green — success
export const primitivesOrange100 = "#FFEDD4"; // California Light — warning bg
export const primitivesOrange500 = "#FE9A00"; // California — warning
export const primitivesRed100 = "#FFDDDB"; // Vermilion Light — error bg
export const primitivesRed600 = "#F54900"; // Vermilion — error
export const semanticColorBrandDefault = "#6D28D9";
export const semanticColorBrandHover = "#7C35EB";
export const semanticColorBrandSubtle = "#F0E9FB";
export const semanticColorBgPage = "#F7F8FA";
export const semanticColorBgSurface = "#FFFFFF";
export const semanticColorBgOverlay = "#1E1E1E";
export const semanticColorTextPrimary = "#0A0A0A";
export const semanticColorTextSecondary = "#717182";
export const semanticColorTextDisabled = "#AEAEAE";
export const semanticColorTextInverse = "#FCFCFC";
export const semanticColorTextBrand = "#6D28D9";
export const semanticColorBorderDefault = "#EBEBEB";
export const semanticColorBorderBrand = "#6D28D9";
export const semanticColorBorderFocus = "#7C35EB";
export const semanticColorStatusSuccess = "#009689";
export const semanticColorStatusSuccessSubtle = "#DCFCE7";
export const semanticColorStatusWarning = "#FE9A00";
export const semanticColorStatusWarningSubtle = "#FFEDD4";
export const semanticColorStatusError = "#F54900";
export const semanticColorStatusErrorSubtle = "#FFDDDB";
export const componentButtonPrimaryBg = "#6D28D9";
export const componentButtonPrimaryBgHover = "#7C35EB";
export const componentButtonPrimaryText = "#FCFCFC";
export const componentButtonSecondaryBg = "#FFFFFF";
export const componentButtonSecondaryBgHover = "#F0E9FB";
export const componentButtonSecondaryText = "#6D28D9";
export const componentButtonSecondaryBorder = "#EBEBEB";
export const componentButtonSecondaryBorderHover = "#6D28D9";
export const componentButtonGhostBg = "#F7F8FA";
export const componentButtonGhostBgHover = "#F0E9FB";
export const componentButtonGhostText = "#6D28D9";
export const componentButtonDisabledText = "#AEAEAE";
export const componentButtonDisabledBorder = "#EBEBEB";
export const spacing1 = "4";
export const spacing2 = "8";
export const spacing3 = "12";
export const spacing4 = "16";
export const spacing5 = "20";
export const spacing6 = "24";
export const spacing8 = "32";
export const spacing10 = "40";
export const spacing12 = "48";
export const radiusSm = "4";
export const radiusMd = "8";
export const radiusLg = "12";
export const radiusXl = "16";
export const radiusFull = "999";
